//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookBorrow
    {
        public int ID { get; set; }
        public DateTime BorrowDate { get; set; }
        public string IDBook { get; set; }
        public int IDReader { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Object Object { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
