//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryManagementPteamEntities : DbContext
    {
        public LibraryManagementPteamEntities()
            : base("name=LibraryManagementPteamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookBorrow> BookBorrows { get; set; }
        public virtual DbSet<Bookshelf> Bookshelves { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Input> Inputs { get; set; }
        public virtual DbSet<Object> Objects { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Suplier> Supliers { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
