//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.BookBorrows = new HashSet<BookBorrow>();
            this.Inputs = new HashSet<Input>();
        }
    
        public string ID { get; set; }
        public string DisplayName { get; set; }
        public string Author { get; set; }
        public string Kind { get; set; }
        public string PublishingYear { get; set; }
        public string Pages { get; set; }
        public string Copies { get; set; }
        public string Catagories { get; set; }
        public Nullable<int> IDBookshelf { get; set; }
        public Nullable<int> IDSuplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookBorrow> BookBorrows { get; set; }
        public virtual Bookshelf Bookshelf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Input> Inputs { get; set; }
        public virtual Suplier Suplier { get; set; }
    }
}
